# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainView.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainView(object):
    def setupUi(self, MainView):
        MainView.setObjectName("MainView")
        MainView.setWindowModality(QtCore.Qt.ApplicationModal)
        MainView.setEnabled(True)
        MainView.resize(600, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainView.sizePolicy().hasHeightForWidth())
        MainView.setSizePolicy(sizePolicy)
        MainView.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        MainView.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F:/FFOutput/未标题-1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainView.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainView)
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonRun = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonRun.setGeometry(QtCore.QRect(250, 160, 100, 40))
        self.ButtonRun.setObjectName("ButtonRun")
        self.groupBoxInput = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxInput.setEnabled(True)
        self.groupBoxInput.setGeometry(QtCore.QRect(40, 20, 521, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxInput.sizePolicy().hasHeightForWidth())
        self.groupBoxInput.setSizePolicy(sizePolicy)
        self.groupBoxInput.setObjectName("groupBoxInput")
        self.lableCurtainIP = QtWidgets.QLabel(self.groupBoxInput)
        self.lableCurtainIP.setGeometry(QtCore.QRect(30, 30, 72, 15))
        self.lableCurtainIP.setObjectName("lableCurtainIP")
        self.labelTransIP = QtWidgets.QLabel(self.groupBoxInput)
        self.labelTransIP.setGeometry(QtCore.QRect(30, 80, 72, 15))
        self.labelTransIP.setObjectName("labelTransIP")
        self.textTransIP = QtWidgets.QTextBrowser(self.groupBoxInput)
        self.textTransIP.setGeometry(QtCore.QRect(110, 70, 241, 31))
        self.textTransIP.setObjectName("textTransIP")
        self.textCurtainIP = QtWidgets.QTextBrowser(self.groupBoxInput)
        self.textCurtainIP.setGeometry(QtCore.QRect(110, 20, 241, 31))
        self.textCurtainIP.setObjectName("textCurtainIP")
        self.labelCurtainPort = QtWidgets.QLabel(self.groupBoxInput)
        self.labelCurtainPort.setGeometry(QtCore.QRect(360, 30, 72, 15))
        self.labelCurtainPort.setObjectName("labelCurtainPort")
        self.labelTransPort = QtWidgets.QLabel(self.groupBoxInput)
        self.labelTransPort.setGeometry(QtCore.QRect(360, 80, 72, 15))
        self.labelTransPort.setObjectName("labelTransPort")
        self.textTransPort = QtWidgets.QTextBrowser(self.groupBoxInput)
        self.textTransPort.setGeometry(QtCore.QRect(430, 70, 81, 31))
        self.textTransPort.setObjectName("textTransPort")
        self.textCurtainPort = QtWidgets.QTextBrowser(self.groupBoxInput)
        self.textCurtainPort.setGeometry(QtCore.QRect(430, 20, 81, 31))
        self.textCurtainPort.setObjectName("textCurtainPort")
        self.groupBoxController = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxController.setGeometry(QtCore.QRect(30, 220, 521, 191))
        self.groupBoxController.setObjectName("groupBoxController")
        self.ButtonOn = QtWidgets.QPushButton(self.groupBoxController)
        self.ButtonOn.setGeometry(QtCore.QRect(320, 40, 131, 41))
        self.ButtonOn.setObjectName("ButtonOn")
        self.ButtonOff = QtWidgets.QPushButton(self.groupBoxController)
        self.ButtonOff.setGeometry(QtCore.QRect(320, 110, 131, 41))
        self.ButtonOff.setObjectName("ButtonOff")
        self.OutPutText = QtWidgets.QLabel(self.groupBoxController)
        self.OutPutText.setGeometry(QtCore.QRect(90, 70, 221, 41))
        self.OutPutText.setObjectName("OutPutText")
        self.groupBoxController.raise_()
        self.groupBoxInput.raise_()
        self.ButtonRun.raise_()
        MainView.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainView)
        self.statusbar.setObjectName("statusbar")
        MainView.setStatusBar(self.statusbar)

        self.retranslateUi(MainView)
        QtCore.QMetaObject.connectSlotsByName(MainView)

    def retranslateUi(self, MainView):
        _translate = QtCore.QCoreApplication.translate
        MainView.setWindowTitle(_translate("MainView", "物联网智能教室"))
        self.ButtonRun.setText(_translate("MainView", "PushButton"))
        self.groupBoxInput.setTitle(_translate("MainView", "GroupBox"))
        self.lableCurtainIP.setText(_translate("MainView", "TextLabel"))
        self.labelTransIP.setText(_translate("MainView", "TextLabel"))
        self.labelCurtainPort.setText(_translate("MainView", "TextLabel"))
        self.labelTransPort.setText(_translate("MainView", "TextLabel"))
        self.groupBoxController.setTitle(_translate("MainView", "GroupBox"))
        self.ButtonOn.setText(_translate("MainView", "PushButton"))
        self.ButtonOff.setText(_translate("MainView", "PushButton"))
        self.OutPutText.setText(_translate("MainView", "TextLabel"))

